
mutation createFederal {
  createFederal(input: {
    name: "AVALOQ"
    fullName: "AVALOQ GROUP"
    
  }) {
    uuid
  }
}

mutation createCloudProvider {
  createCloudProvider(input: {
    name: "IBM"
    fullName: "IBM Cloud"
    
  }){
    __typename
    uuid
  }
  
}


mutation createCloudEstate {
  createCloudEstate(input: {
    name: "AVALOQ-AWS-ESTATE"
    description:"Management Account of Avaloq Group with AWS"
    federal: "AGRO"
    cloudProvider: "AWS"
    federalEmailAddress: "aws@avaqlo.com"
    cloudEstateCid: "898024814010"
    
  }){
    uuid
  }
}


query cloudEstate {
  cloudEstateByUUID(uuid: "ce95105a-9e7c-4e78-8082-d503f95c4b4f") {
    name 
  }
}

mutation createCloudEstatePolicy {
  createCloudEstatePolicyWithCid(input: {
    name: "TAG-POLICY-FOR-AEVO-AWS-BY-BY-ARN"
    description: "Federal Tag Policy for AVALOQ and AWS"
    cloudEstate: "AVALOQ-AWS-ESTATE"
    policyType: "TAG"
    policyCid: "arn:aws:organizations::898024814010:policy/o-py48lgs0w1/tag_policy/p-953m46re9l"
    
  }) {
    uuid
  }
}

mutation createCloudEstatePolicy($tags: JSON!) {
  createCloudEstatePolicyWithJson(input: {
    name: "TAG-POLICY-FOR-AEVO-AWS-BY-JSON"
    description: "Federal Tag Policy for AEVEO and AWS-1"
    cloudEstate: "AEVO-AWS-ESTATE"
    policyType: "TAG"
    policyJson: $tags
    
  }) {
    uuid
  }
}

{
  "tags": "{\"CostCenter\":{\"tag_key\":{\"@@assign\":\"CostCenter\",\"@@operators_allowed_for_child_policies\":[\"@@none\"]}},\"Project\":{\"tag_key\":{\"@@assign\":\"Project\",\"@@operators_allowed_for_child_policies\":[\"@@none\"]}}}"
}

mutation createClient{
  createClient(input: {
    name: "DEPOBANK"
    fullName: "Depot Bank"
    
  }) {
    id,
    uuid
    
  }
}

mutation createStage{
  createStage(input: {
    name: "uat"
    description: "The service is in user acceptance testing, data is not persisted."
    
  }) {
    id,
    uuid
    
  }
}

mutation createClass{
  createClass(input: {
    name: "trial"
    description: "The service represents a sponsored proof-of-concept and has to abide to budget restrictions."
    
  }) {
    id,
    uuid
    
  }
}


mutation createResident {
  createResident(input: {
    name: "cloud-control",
    description: "Vending Machine for Sprint Dev"
    purchaseOrder: "PONO"
    emailAddress: "cloudcontrol.ch@gmail.com"
    client: "AEVO"
    cloudEstate: "AEVO-AWS-ESTATE"
    class: "free"
    stage: "uat"
    
  }
  ) {
    id
    uuid
    cloudEstateCid
  }
}

----

query residents {
  residents {
    name,
  }
}

mutation createUser {
  createUser(input: {
    name: "vending-iam-user"
    description: "vending-iam-user"
    resident: "cloud-control"

  }) {
    id
    uuid
  }
}



-- VENDDING MACHINE FOR THE SPRINT REVIEW READINESS

mutation createResident {
  createResident(input: {
    name: "cloud-control-sprint-review-pre-test",
    description: "Vending Machine for Sprint Pre-Test"
    purchaseOrder: "PONO"
    emailAddress: "cloudcontrol.ap@gmail.com"
    renter: "AEVO"
    cloudEstate: "AVALOQ-AWS-ESTATE"
    cloudEstatePolicies: "TAG-POLICY-FOR-AEVO-AWS-BY-BY-ARN"
    class: "free"
    stage: "uat"
    
  }
  ) {
    id
    uuid
    cloudEstateCid
  }
}


mutation createUser {
  createUser(input: {
    name: "review-iam-user"
    description: "review-iam-user"
    resident: "cloud-control-sprint-review-pre-test"

  }) {
    id
    uuid
  }
}


mutation createResident {
  createResident(input: {
    name: "cloud-control-sprint",
    description: "Vending Machine for Sprint"
    purchaseOrder: "PONO"
    emailAddress: "federal.org.evo@gmail.com"
    renter: "AEVO"
    cloudEstate: "AVALOQ-AWS-ESTATE"
    cloudEstatePolicies: "TAG-POLICY-FOR-AEVO-AWS-BY-BY-ARN"
    class: "free"
    stage: "uat"
    
  }
  ) {
    id
    uuid
    cloudEstateCid
  }
}


mutation createUser {
  createUser(input: {
    name: "review-sprint-user"
    description: "review-sprint-user"
    resident: "cloud-control-sprint"

  }) {
    id
    uuid
  }
}
