
query federals {
 	federals {
    uuid
    id
    name
    fullName
  }
}

query cloudProvider {
  cloudProviders {
   uuid
   id
   name
   fullName
 }
}

query cloudEstate {
  cloudEstates {
   uuid
   id
   name
 }
}