// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Class struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type Client struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	FullName string `json:"fullName"`
}

type CloudProvider struct {
	ID      string `json:"id"`
	Name    string `json:"name"`
	RootCid string `json:"rootCid"`
}

type NewResident struct {
	Name              string `json:"name"`
	Description       string `json:"description"`
	PurchaseOrderID   string `json:"purchaseOrderId"`
	ClientName        string `json:"clientName"`
	CloudProviderName string `json:"cloudProviderName"`
	ClassName         string `json:"className"`
	StageName         string `json:"stageName"`
}

type Resident struct {
	ID              string `json:"id"`
	Name            string `json:"name"`
	Description     string `json:"description"`
	PurchaseOrderID string `json:"purchaseOrderId"`
	Client          string `json:"client"`
	CloudProvider   string `json:"cloudProvider"`
	ResidentCid     string `json:"residentCid"`
	RootCid         string `json:"rootCid"`
	Class           string `json:"class"`
	Stage           string `json:"stage"`
	CreatedAt       string `json:"createdAt"`
	CreatedBy       string `json:"createdBy"`
	UpdatedAt       string `json:"updatedAt"`
	UpdatedBy       string `json:"updatedBy"`
}

type Stage struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
}
