// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Class struct {
	ID          string `json:"id"`
	UUID        string `json:"uuid"`
	Name        string `json:"name"`
	Description string `json:"description"`
	CreatedAt   string `json:"createdAt"`
	CreatedBy   string `json:"createdBy"`
	UpdatedAt   string `json:"updatedAt"`
	UpdatedBy   string `json:"updatedBy"`
}

type CloudEstate struct {
	ID                  string `json:"id"`
	UUID                string `json:"uuid"`
	Name                string `json:"name"`
	Description         string `json:"description"`
	Federal             string `json:"federal"`
	CloudProvider       string `json:"cloudProvider"`
	FederalEmailAddress string `json:"federalEmailAddress"`
	CloudEstateCid      string `json:"cloudEstateCid"`
	CreatedAt           string `json:"createdAt"`
	CreatedBy           string `json:"createdBy"`
	UpdatedAt           string `json:"updatedAt"`
	UpdatedBy           string `json:"updatedBy"`
}

type CloudEstatePolicy struct {
	ID          string `json:"id"`
	UUID        string `json:"uuid"`
	Name        string `json:"name"`
	Description string `json:"description"`
	CloudEstate string `json:"cloudEstate"`
	PolicyType  string `json:"policyType"`
	PolicyCid   string `json:"policyCid"`
	PolicyJSON  string `json:"policyJson"`
	CreatedAt   string `json:"createdAt"`
	CreatedBy   string `json:"createdBy"`
	UpdatedAt   string `json:"updatedAt"`
	UpdatedBy   string `json:"updatedBy"`
}

type CloudProvider struct {
	ID        string `json:"id"`
	UUID      string `json:"uuid"`
	Name      string `json:"name"`
	FullName  string `json:"fullName"`
	CreatedAt string `json:"createdAt"`
	CreatedBy string `json:"createdBy"`
	UpdatedAt string `json:"updatedAt"`
	UpdatedBy string `json:"updatedBy"`
}

type Federal struct {
	ID        string `json:"id"`
	UUID      string `json:"uuid"`
	Name      string `json:"name"`
	FullName  string `json:"fullName"`
	CreatedAt string `json:"createdAt"`
	CreatedBy string `json:"createdBy"`
	UpdatedAt string `json:"updatedAt"`
	UpdatedBy string `json:"updatedBy"`
}

type NewClass struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

type NewCloudEstate struct {
	Name                string `json:"name"`
	Description         string `json:"description"`
	Federal             string `json:"federal"`
	CloudProvider       string `json:"cloudProvider"`
	FederalEmailAddress string `json:"federalEmailAddress"`
	CloudEstateCid      string `json:"cloudEstateCid"`
}

type NewCloudEstatePolicyWithCid struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	CloudEstate string `json:"cloudEstate"`
	PolicyType  string `json:"policyType"`
	PolicyCid   string `json:"policyCid"`
}

type NewCloudEstatePolicyWithJSON struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	CloudEstate string `json:"cloudEstate"`
	PolicyType  string `json:"policyType"`
	PolicyJSON  string `json:"policyJson"`
}

type NewCloudProvider struct {
	Name     string `json:"name"`
	FullName string `json:"fullName"`
}

type NewFederal struct {
	Name     string `json:"name"`
	FullName string `json:"fullName"`
}

type NewRenter struct {
	Name     string `json:"name"`
	FullName string `json:"fullName"`
}

type NewResident struct {
	Name                string    `json:"name"`
	Description         string    `json:"description"`
	PurchaseOrder       string    `json:"purchaseOrder"`
	EmailAddress        string    `json:"emailAddress"`
	CloudEstate         *string   `json:"cloudEstate"`
	CloudEstatePolicies []*string `json:"cloudEstatePolicies"`
	Renter              string    `json:"renter"`
	Class               string    `json:"class"`
	Stage               string    `json:"stage"`
}

type NewStage struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

type NewUser struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Resident    string `json:"resident"`
}

type Renter struct {
	ID        string `json:"id"`
	UUID      string `json:"uuid"`
	Name      string `json:"name"`
	FullName  string `json:"fullName"`
	CreatedAt string `json:"createdAt"`
	CreatedBy string `json:"createdBy"`
	UpdatedAt string `json:"updatedAt"`
	UpdatedBy string `json:"updatedBy"`
}

type Resident struct {
	ID                  string    `json:"id"`
	UUID                *string   `json:"uuid"`
	Name                string    `json:"name"`
	Description         string    `json:"description"`
	PurchaseOrder       string    `json:"purchaseOrder"`
	EmailAddress        string    `json:"emailAddress"`
	Renter              string    `json:"renter"`
	CloudProvider       string    `json:"cloudProvider"`
	ResidentCid         string    `json:"residentCid"`
	CloudEstate         string    `json:"cloudEstate"`
	CloudEstateCid      string    `json:"cloudEstateCid"`
	CloudEstatePolicies []*string `json:"cloudEstatePolicies"`
	Class               string    `json:"class"`
	Stage               string    `json:"stage"`
	CreatedAt           string    `json:"createdAt"`
	CreatedBy           string    `json:"createdBy"`
	UpdatedAt           string    `json:"updatedAt"`
	UpdatedBy           string    `json:"updatedBy"`
}

type Stage struct {
	ID          string `json:"id"`
	UUID        string `json:"uuid"`
	Name        string `json:"name"`
	Description string `json:"description"`
	CreatedAt   string `json:"createdAt"`
	CreatedBy   string `json:"createdBy"`
	UpdatedAt   string `json:"updatedAt"`
	UpdatedBy   string `json:"updatedBy"`
}

type Tag struct {
	ID        string  `json:"id"`
	UUID      string  `json:"uuid"`
	TagFamily *string `json:"tagFamily"`
	Tag       string  `json:"tag"`
	CreatedAt string  `json:"createdAt"`
	CreatedBy string  `json:"createdBy"`
	UpdatedAt string  `json:"updatedAt"`
	UpdatedBy string  `json:"updatedBy"`
}

type TagFamily struct {
	ID        string `json:"id"`
	UUID      string `json:"uuid"`
	Name      string `json:"name"`
	CreatedAt string `json:"createdAt"`
	CreatedBy string `json:"createdBy"`
	UpdatedAt string `json:"updatedAt"`
	UpdatedBy string `json:"updatedBy"`
}

type User struct {
	ID          string `json:"id"`
	UUID        string `json:"uuid"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Resident    string `json:"resident"`
	UserCid     string `json:"userCid"`
	CreatedAt   string `json:"createdAt"`
	CreatedBy   string `json:"createdBy"`
	UpdatedAt   string `json:"updatedAt"`
	UpdatedBy   string `json:"updatedBy"`
}
